# Generated by Django 5.2.4 on 2025-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Api', '0007_rename_emainl_notifications_usersettings_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='event_type',
            field=models.CharField(choices=[('register', 'User Registration'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('logout', 'Logout'), ('account_deletion', 'Account Deletion')], max_length=50),
        ),
    ]
