# Generated by Django 5.2.4 on 2025-07-19 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='parents_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='notes.note'),
        ),
    ]
