# Generated by Django 5.2.4 on 2025-07-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_parents_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='parents_note',
            new_name='parent',
        ),
    ]
